import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Providers from "@/providers/Providers";
import CustomNavbar from "@/components/UI/CustomNavbar";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Calculadora Simplex",
    description: "Generated by create next app",
};
export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full bg-slate-50 dark:bg-customDarkBg`}>
        <Providers>
            <CustomNavbar/>
            <main className="min-h-full dark:text-white dark:bg-customDarkBg">
                {children}
            </main>
        </Providers>
        </body>
        </html>
    );
}